### PR TITLE
Update main.json - German translation

### PR DESCRIPTION
**Pull request by giddyhup**
Added missing translations. Fine-tuned existing ones.

### CODE REVIEW

**Comment by vegeta897** [comment]
Thank you so much for this!

If it isn't too much trouble, could you add these 2 missing translations to the file as well: 

https://github.com/vegeta897/word-peaks/blob/main/src/lib/translations/en/main.json#L82

https://github.com/vegeta897/word-peaks/blob/main/src/lib/translations/en/main.json#L85

I started putting new untranslated strings into the English file only since they work as a fallback for untranslated strings that way, but maybe this makes it more confusing for contributors.

You may also add yourself to the translator credits in the README!

**Comment by vegeta897** [comment]
Many thanks! 😊

**Comment by vegeta897** [comment]
Ah crap, I forgot about `options.tile_sharpness` 😩

**Comment by giddyhup** [comment]
No biggie, "Kachelschärfe".

**Comment by vegeta897** [comment]
Haha I am so incompetent right now. I did not forget it and neither did you, but what I did not do was actually _use_ the string in the app!

Thanks for putting up with me, you're a saint.

**Pull request merged**
