### PR TITLE
:fire: Remove inappropriate words from target

### PR DESCRIPTION
**Pull request by medubelko**
# Removed

- slave
- urine
- nancy
- fatty
- moron
- idiot
- randy
- prick
- horny
- ponce
- pubis
- pussy
- nance
- tubby

# Other candidates for removal
@vegeta897 Please also review the following candidates.

#### Bordering on distasteful or profane
- tumor
- bowel
- sperm
- fetal
- fetus
- edema
- woody
- vulva
- ovary
- ileum
- enema
- sissy
- hymen
- glans
- ileus
- gonad

#### Rare or archaic usage or spelling in English
- chile
- mater
- spake
- leach
- apres
- seton
- tanto
- waugh
- largo
- durst
- atman
- mille
- libri
- madre
- bonne
- lexis
- frere
- crore
- moira
- emmet
- speer
- tilak
- hakim
- parol
- scrip
- mamie
- tutti
- sorel
- chevy
- ulama
- stupa
- kraal
- satis
- usque
- khadi
- mufti
- prise
- gutta
- sherd
- objet
- finis
- bennes
- sophy
- altho
- molto
- begum
- logon
- milch
- doeth
- neath
- pacha
- dewan
- fille
- rebbe
- britt
- dixit
- nisei
- leges
- licht
- hadst
- diwan
- mezzo
- matin
- magus
- mucho
- taluk
- vertu
- murry
- manas
- devas
- thorp
- aline
- dolce
- blume
- hafiz
- djebel
- seder
- parle
- devel
- mache
- bruit
- sepoy
- ameer
- griff
- kluge
- bally
- geste

#### Proper nouns
- venus
- torah
- franc
- sodom
- calif
- libra
- shawn
- orang
- metis
- debye
- nubia
- tatar
- peres
- nicol
- pekin
- varna
- ostia
- ruble
- penna
- hants
- rabat
- lindy
- pyrex

#### Multiple spellings
- saber/sabre

### CODE REVIEW

**Comment by medubelko** [comment]
If you turn on reviews it'll make managing PRs easier.

**Review by vegeta897 — CHANGES_REQUESTED** [review]
Great work, thank you! Please go ahead and remove the borderline, archaic, and proper noun lists from this file as well.

Edit: And saber/sabre too! ⚔

**Comment by medubelko** [comment]
> And saber/sabre too!

Keep the American spelling?

**Comment by vegeta897** [comment]
> Keep the American spelling?

May as well remove both. Any word that could potentially make the player say "oh that's not how it's spelled" is bad.

Keep in mind this is not the list of any valid word they can type.

**Comment by vegeta897** [comment]
Additional words to remove:
- natty
- mezzo
- nisei
- glial
- annul
- situs
- venal
- billy

Maybe remove?
- xenon

**Review by vegeta897 — APPROVED** [review]

**Review by vegeta897 — CHANGES_REQUESTED** [review]
More:

- enrol
- etude
- hilar
- ilium
- sower
- umber
- buffy

**Review by vegeta897 — CHANGES_REQUESTED** [review]
Yet more:
- cubit

**Comment by vegeta897** [comment]
Don't make any more commits; I have one pending that I want to push but I need you to edit the PR to allow edits from maintainers.

**Review by vegeta897 — APPROVED** [review]

**Pull request merged**
